### PR TITLE
provider: Support DiskSize for GCE

### PR DESCRIPTION
**Pull request by HongjianZhang**
Before this patch, DiskSize was only supported for AWS. This patch
allows booting machines with user-specified DiskSize on GCE.

### CODE REVIEW

**Comment by ejj** [comment]
How did you test this btw?

**Comment by kklin** [comment]
The `DiskSize` should also be properly set when `List` is called

**Comment by HongjianZhang** [comment]
I think each machine can be attached multiple disks, each disk having a diskSize. Since the DiskSize property of db.Machine has type int, should that property simply be set as the sum of all the disks?

**Comment by ejj** [comment]
That definitely won't work.  Have a look at how the caller uses List and see if you can figure out a solution for that situation.

**Comment by HongjianZhang** [comment]
I think I misunderstood how `List()` is used. I noticed that the `parseDiskSize` function in the Amazon code only extracts the size of the first disk from the BlockDeviceMappings. I am not sure why, but I did something similar here, where I only extract the size of the first attached disk. Can someone confirm this?

**Comment by HongjianZhang** [comment]
Need some more changes before it can be reviewed again.

**Comment by kklin** [comment]
Closing this since nobody is really making use of the DiskSize feature, and this PR isn't ready to be merged yet.

**Pull request closed without merging**
