### PR TITLE
bindings: Use allowTraffic instead of allowFrom/allow

### PR DESCRIPTION
**Pull request by aegamesi**
This change updates this blueprint to use the new allowTraffic method
instead of the now deprecated allowFrom and allow methods.

### CODE REVIEW

**Comment by kklin** [comment]
I think there's an outdated use of the API in the README that needs to be updated

**Comment by luise** [comment]
It would also be awesome if you could update the examples in the docs!

**Comment by kklin** [comment]
This PR should fix the part of the build that's failing because of Django https://github.com/kelda/kelda/pull/1358

**Comment by aegamesi** [comment]
@kklin I've fixed all of the non-code references to allowFrom

**Comment by kklin** [comment]
@aegamesi build is still failing because you omitted the dest here  https://github.com/kelda/kelda/pull/1354/files#diff-cd4719279a050dcc6fbd6f4afe3cb8a9R51

**Comment by aegamesi** [comment]
oof, fixed @kklin

**Pull request merged**
